name: Org Metrics

on:
  schedule:
    - cron: "17 1 * * *"   # daily 01:17 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Org target
          user: SantosMods
          template: classic
          base: header, repositories
          config_timezone: America/New_York

          # IMPORTANT: org mode
          # See: https://github.com/lowlighter/metrics (supports organizations)
          plugin_achievements: no
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 12

          plugin_followup: yes
          plugin_followup_sections: repositories, user

          plugin_repositories: yes
          plugin_repositories_featured: SantosMods/UrbanPlus_World-Reimagined

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_indepth: yes

          plugin_stargazers: yes
          plugin_forks: yes
